# Generated by Django 3.2.8 on 2021-10-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_delete_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='description',
        ),
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(default='jenny'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
